apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: intellinexus

commonLabels:
  app.kubernetes.io/name: intellinexus
  app.kubernetes.io/part-of: intellinexus-platform

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
