apiVersion: v1
kind: Namespace
metadata:
  name: intellinexus
  labels:
    app.kubernetes.io/name: intellinexus
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
