apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: intellinexus
  labels:
    app.kubernetes.io/name: intellinexus
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: intellinexus
