apiVersion: v1
kind: Service
metadata:
  name: {{ include "intellinexus.fullname" . }}
  labels:
    {{- include "intellinexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "intellinexus.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "intellinexus.fullname" . }}
  labels:
    {{- include "intellinexus.labels" . | nindent 4 }}
